trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
  containers:
    - container: azurite
      image: mcr.microsoft.com/azure-storage/azurite

services:
  azurite: azurite

steps:
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH

- script: |
    conda install -y -c conda-forge python=3 azure-datalake-store azure-storage-blob fsspec pytest requests
  displayName: 'Install dependencies'

- script: |
    pytest
  displayName: 'Run Dask Benchmarks'
