version: '3'
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
    - "10000:10000"
  test:
    build: .
    links:
      - azurite
    command: ["pytest", "--host=azurite:10000", "adlfs"]
